### PR TITLE
Added support for a custom build message

### PR DESCRIPTION
**Pull request by lucaslt89**

### CODE REVIEW

**Comment by lucaslt89** [comment]
@kanari3 I opened this PR to add support to specify the build message. The default one was "Bitrise build", but it'd be good to allow users to specify this message as part of the step in bitrise

**Comment by lucaslt89** [comment]
@kanari3 I think you need to create a new tag 0.0.3 to make the step usable in Bitrise 🤔?

Thanks for the quick reply btw!

**Comment by kanari3** [comment]
@lucaslt89 
Yes, I'm going to update Readme.md and then send a PR to bitrise.
Please wait a little longer.

**Comment by kanari3** [comment]
@lucaslt89 
thanks. I had to fix the indentation of the yml file.
https://github.com/kanari3/bitrise-step-appcenter-ipa-upload/pull/5/files

bitrise-steplib PR
https://github.com/bitrise-io/bitrise-steplib/pull/2490

It will be released soon!

**Comment by kanari3** [comment]
@lucaslt89 
Your PR has been merged!

**Pull request merged**
